---
title: "An Introduction to R"
output: 
  html_document:
    toc: no
---

\  

### Course Introduction

\  

Welcome to our *Introduction to R* training course. During this course we hope to introduce you to using R, an interactive environment for statistical computing. R in itself is not difficult to learn, but just like any new language the initial learning curve can be a little steep and you will need to use it frequently otherwise it’s easy to forget. 

A few notes about this course. We have tried to simplify the content of this course as much as possible and have based it on 15 years experience teaching (and learning!) R. It is not intended as an introductory statistics course, although we will be using some basic statistics to highlight some of R’s capabilities. Our aim is to help you climb the initial learning curve and provide you with the basic skills to enable you to further your experience in using R. We have included a number of practical [exercises](exercises.html) for you to work through during the course and encourage you complete these in your own time - you certainly won’t learn how to use R by watching other people do it! 

\  

----

### FAQ

\  

#### How do I use this website?
How you use this website to support your learning and understanding of R is of course up to you. Having said that here are few pointers that have worked for people in the past. The first thing you will need to do is download and install both R and RStudio on your computer. Take a look at the **<i class="fa fa-cog" aria-hidden="true"></i> Setup** link on the navbar at the top of this page for further instructions on how to set up your computer and download the required datasets. At the heart of this course is our 'Introduction to R book' which you can find by clicking on the **<i class="fa fa-book" aria-hidden="true"></i> R Book** link in the navbar. The book is split into 9 Chapters which cover different aspects of using R and RStudio, from general orientation, basic R operations, importing and manipulating data, plotting data, programming in R, R markdown and using version control.  During this course we will be covering the first four Chapters only. You can test your understanding of each of these components by completing the associated exercises which you can find by clicking on **<i class="fa fa-file-contract" aria-hidden="true"></i> Exercises**. You will also find the solutions to the exercises here but we suggest that you don't peek at the solutions too quickly and only use them to confirm your answers or if you get stuck and feel like throwing your keyboard out of the window! There are also some additional resources such as lecture slides we use during our in person courses, short how-to videos walking you through some important topics which you can find in the **<i class="fa fa-university" aria-hidden="true"></i> Learn R** link. We've also created some stand alone tutorials covering topics such as RStudio Projects, R markdown and version control using Git and GitHub which can be found under the **<i class="fa fa-desktop" aria-hidden="true"></i> Tutorials** link. We suggest that you take a look at the tutorials once you've finished the core part of this course.

\  

#### What are the pre-requisites for this course?
This course assumes no previous experience or knowledge of using either R or RStudio. It also doesn't assume any knowledge of programming or using a command-line interface, but if you have some experience, the content won’t come as so much of a shock. But don’t panic. Command-line interfaces and programming languages like R are incredibly powerful and will be utterly transformative to your research. There’s a learning curve, and it’s pretty steep in the beginning, but it’s surmountable and the payoff is worth it!

\  

#### What is the course timetable?
See the course [syllabus](syllabus.html) for a general outline of the course content and timing. The course will start at 09:30 each morning and finish at 17:00. We will break for a one hour lunch break around 12:30. However, everyone learns R in their own way and at their own pace so this syllabus should be treated as indicative rather than absolute. There will also be plenty of opportunities to take short breaks during the course and we will also have a couple of 30 minute sessions on robust and reproducible research practices.  

\  

#### Where is the course held?
This course will be run entirely online this year due to National Government Covid-19 restrictions. All interactive live sessions will be run using Blackboard Collaborate via [MyAberdeen](https://abdn.blackboard.com/). During these live sessions you will all be working in the main meeting room as you work through the associated course exercises. If you have a question, or get stuck you'll be able to get 1:1 support from one of the course instructors in a smaller breakout group. More information about this setup will be provided during the first session on Wednesday 6^th^ April 2022.   

\  

#### Do I need my own computer?

<!--
No. We will provide desktop computers for those who do not wish to bring their own laptops to the course. All of the desktops will have both R and RStudio already installed but please bring along a USB flash drive to save your work. If you require a desktop computer then please make sure you have registered for a UoA visitor computing account prior to the start of the course (contact [Izzie Buchanan](People.html) for further details). Having said that, if you have a laptop (Mac or Windows) we encourage you to bring it to the course. Please take a look at the **[Setup<i class="fa fa-cog" aria-hidden="true"></i>](setup.html)** link on the navbar at the top for further instructions on how to set up your laptop prior to the course starting.
-->

Yes. As we'll be running the course online this year you'll need your own computer with internet access. Please take a look at the **[<i class="fa fa-cog" aria-hidden="true"></i>Setup](setup.html)** link on the navbar at the top for further instructions on how to set up your computer prior to the course starting. Don't worry, you don't need a particularly powerful computer to install R and RStudio so anything from the last 5 years or so should be fine. What you will need is a reasonably stable internet connection to participate in the live Blackboard Collaborate sessions. If you think that your internet connection may not be up to it then please contact [Alex](People.html) to discuss alternatives.

\  

#### Why are you not teaching us 'tidyverse'?
We have thought long and hard about whether to teach this course only using the ['tidyverse'](https://www.tidyverse.org/){target='_blank'} collection of packages and approaches (if you've never heard of 'tidyverse' before then don't worry about it!). Although we do cover the tidyverse package 'ggplot2', we decided that it was more important that by the end of the course you have a good fundamental grasp of base R which will provide you with the foundation to go on and learn 'tidyverse' approaches in your own time (if you want to). Having said that, if you have previous experience using 'tidyverse' then feel free to complete the course exercises using this approach. 

\  

#### I don't like/want to use RStudio
Not a problem. Feel free to use the IDE or script editor of your choice. One of the great things about R is that *YOU* decide how you want to use it. See [Chapter 1](https://alexd106.github.io/Rbook/alternatives-to-rstudio.html) of our 'Introduction to R' book for some suggested alternatives.

\  

#### What do I do once I finish the course?
The only way to get more comfortable using R is to use R! We strongly suggest that having completed this course you start using R to summarise, manipulate, plot and analyse your own data as soon as possible. If you don't have any data yet, then ask your friends/supervisor/family for some (I'm sure they will be delighted!) or follow one of the many excellent tutorials available online (see the [resources](resources.html) page for more information). Our suggestion to you, is that whilst you are getting to grips with R, uninstall any other statistics software you have on your computer and only use R. This may seem a little extreme but will hopefully remove the temptation to ‘just do it quickly’ in a more familiar environment and consequently slow down your learning of R. Believe us, anything you can do in your existing statistics software package you can do in R (often better and more efficiently).

\  

